# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-ModBT
version:      0.010
version_from: lib/Apache/ModBT.pm
installdirs:  site
requires:
    Net::BitTorrent::LibBTT:       0.010

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
